### PR TITLE
Add possibility to add new attribute

### PR DESCRIPTION
**Pull request by davidfuhr**
I'd like to add a new attribute to wildfly. This is the jboss cli command I use

```
/subsystem=mail/mail-session="postbox":add(jndi-name="java:/mail/postbox",debug=true)
```

I did not find a way to do this using this cookbooks. I'm not very familiar with ruby, is my PR going in the right direction?

### CODE REVIEW

**Comment by bdwyertech** [comment]
Doesn't this `:add` action do the same thing as `:set`?

**Comment by davidfuhr** [comment]
I did not find a way to add a new mail-session with the write-attribute command. As far as I understand the write-attribute is fine to update/set a single property, but not for adding resources. https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.0/html-single/management_cli_guide/#update_attribute

**Comment by dyba** [comment]
@bdwyertech Will you merge this once the tests are passing?

**Comment by rbellamy** [comment]
I'm interested in seeing this too...

**Pull request merged**
